version: "3.9"

services:
  app:
    build:
      context: .
      target: development  # Change to 'production' for production use
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENV=development  # Change to 'production' when needed
